import os
import uuid
import json
import time
import threading
import smtplib
import ssl
import requests
from email.mime.text import MIMEText
from datetime import datetime, timezone
from google.cloud import bigquery
from dotenv import load_dotenv

load_dotenv()

_PROJECT = os.getenv("GCP_PROJECT_ID")
_DATASET = os.getenv("BIGQUERY_DATASET")
_TABLE = f"{_PROJECT}.{_DATASET}.approved_actions"
_POLL_INTERVAL = 10

_GMAIL_USER = os.getenv("GMAIL_USER")
_GMAIL_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")

_FIVETRAN_API_KEY = os.getenv("FIVETRAN_API_KEY")
_FIVETRAN_API_SECRET = os.getenv("FIVETRAN_API_SECRET")
_FIVETRAN_CONNECTOR_ID = os.getenv("FIVETRAN_CONNECTOR_ID")

_client = None


def _get_client() -> bigquery.Client:
    global _client
    if _client is None:
        _client = bigquery.Client(project=_PROJECT)
    return _client


def _send_email(to: str, subject: str, body: str) -> None:
    if not _GMAIL_USER or not _GMAIL_PASSWORD:
        print(f"action_agent: email skipped (GMAIL_USER or GMAIL_PASSWORD not set)")
        return

    try:
        context = ssl.create_default_context()
        msg = MIMEText(body, "plain", "utf-8")
        msg["Subject"] = subject
        msg["From"] = _GMAIL_USER
        msg["To"] = to
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(_GMAIL_USER, _GMAIL_PASSWORD)
            server.send_message(msg)
        print(f"action_agent: email sent to {to} — {subject}")
    except Exception as e:
        print(f"action_agent: email send failed to {to}: {e}")
        raise


def _repair_connector(connector_id: str, connector_status: dict) -> tuple[bool, str]:
    if not connector_id:
        return False, "no connector_id available"
    base_url = f"https://api.fivetran.com/v1/connectors/{connector_id}"
    auth = (_FIVETRAN_API_KEY, _FIVETRAN_API_SECRET)
    try:
        r = requests.patch(base_url, json={"paused": False}, auth=auth, timeout=10)
        r.raise_for_status()
    except Exception as e:
        return False, f"unpause failed: {e}"
    try:
        r = requests.post(f"{base_url}/force", json={}, auth=auth, timeout=10)
        r.raise_for_status()
    except Exception as e:
        return False, f"sync trigger failed: {e}"
    return True, "repair triggered: unpaused + sync forced"


def _compose_email_body(action_type: str, payload: dict) -> str:
    now = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    atype = action_type.lower()

    if atype in ("investigate_sensor_anomaly", "sensor_anomaly", "maintenance_email"):
        sensor = payload.get("sensor_name") or payload.get("target") or "an unspecified sensor"
        severity = payload.get("severity", "")
        severity_line = f"Severity Level: {severity}\n" if severity else ""
        findings = (
            payload.get("diagnosis")
            or payload.get("body")
            or payload.get("summary")
            or payload.get("description")
            or payload.get("message")
            or "Please refer to the attached sensor data for details."
        )
        recommended = payload.get("recommended_action") or payload.get("action") or ""
        action_section = f"\nRecommended Action:\n{recommended}\n" if recommended else ""
        return (
            f"Dear Maintenance Team,\n\n"
            f"I am writing to bring to your immediate attention a sensor anomaly that has been detected "
            f"on the factory floor and requires your urgent review.\n\n"
            f"Affected Equipment: {sensor}\n"
            f"{severity_line}"
            f"Detection Time: {now}\n\n"
            f"Findings:\n{findings}\n"
            f"{action_section}\n"
            f"This alert was automatically generated by the Smart Plant AI monitoring system. "
            f"Please review the situation and take appropriate action at your earliest convenience. "
            f"Should you require additional information, please do not hesitate to contact the plant operations team.\n\n"
            f"Yours sincerely,\n"
            f"Smart Plant AI System"
        )

    if atype in ("pipeline_fix", "investigate_pipeline_failure"):
        status = payload.get("connector_status") or {}
        connector = payload.get("connector_id") or (status.get("id") if isinstance(status, dict) else None) or "unknown"
        reason = payload.get("reason") or "an unspecified failure"
        last_sync = payload.get("last_succeeded_at") or ""
        last_sync_line = f"Last Successful Sync: {last_sync}\n" if last_sync else ""
        forensics = payload.get("forensics") or {}
        report = forensics.get("forensics_report") if isinstance(forensics, dict) else None
        forensics_section = f"\nAI Root-Cause Analysis:\n{report}\n" if report else ""
        repair_result = payload.get("repair_result")
        repair_success = payload.get("repair_success")
        if repair_result is not None:
            status_word = "Successful" if repair_success else "Failed"
            repair_section = f"\nRepair Attempt:\n  Status: {status_word}\n  Detail: {repair_result}\n"
        else:
            repair_section = ""
        return (
            f"Dear Data Engineering Team,\n\n"
            f"This is an automated notification regarding a data pipeline failure that has been detected "
            f"and requires your immediate attention.\n\n"
            f"Connector: {connector}\n"
            f"Failure Reason: {reason}\n"
            f"{last_sync_line}"
            f"Detection Time: {now}\n"
            f"{forensics_section}"
            f"{repair_section}\n"
            f"Please investigate and resolve this issue as soon as possible to ensure data continuity "
            f"for plant monitoring operations.\n\n"
            f"Regards,\n"
            f"Smart Plant AI System"
        )

    if atype == "shift_handover":
        content = (
            payload.get("body")
            or payload.get("summary")
            or "Please refer to the shift log for details."
        )
        return (
            f"Dear Incoming Shift Operator,\n\n"
            f"Please find below the automated shift handover summary prepared by the Smart Plant AI system "
            f"for your review before assuming operational responsibility.\n\n"
            f"{content}\n\n"
            f"If you have any questions or require clarification on any of the items above, "
            f"please contact the outgoing shift supervisor.\n\n"
            f"Regards,\n"
            f"Smart Plant AI System"
        )

    content = (
        payload.get("body")
        or payload.get("summary")
        or payload.get("description")
        or json.dumps(payload, indent=2)
    )
    return (
        f"Dear Team,\n\n"
        f"This is an automated notification from the Smart Plant AI monitoring system.\n\n"
        f"{content}\n\n"
        f"Please take appropriate action as required.\n\n"
        f"Regards,\n"
        f"Smart Plant AI System"
    )


def _execute_action(row: dict) -> None:
    payload = json.loads(row["payload"]) if isinstance(row["payload"], str) else row["payload"]
    action_type = row["action_type"]

    print(f"action_agent: executing {action_type} — {payload.get('subject', '')}")

    email_action_types = [
        "maintenance_email",
        "shift_handover",
        "Investigate_Sensor_Anomaly",
        "investigate_sensor_anomaly",
        "sensor_anomaly",
    ]
    pipeline_action_types = ["pipeline_fix", "investigate_pipeline_failure"]

    if action_type in email_action_types or action_type in pipeline_action_types:
        recipient = payload.get("recipient") or os.getenv("ALERT_EMAIL_RECIPIENT", _GMAIL_USER)
        subject = payload.get("subject", action_type)
        if action_type in pipeline_action_types:
            connector_status = payload.get("connector_status") or {}
            connector_id = (
                payload.get("connector_id")
                or (connector_status.get("id") if isinstance(connector_status, dict) else None)
                or _FIVETRAN_CONNECTOR_ID
            )
            success, repair_msg = _repair_connector(connector_id, connector_status)
            payload["repair_result"] = repair_msg
            payload["repair_success"] = success
            subject = f"[Pipeline {'Repaired' if success else 'Repair Failed'}] {subject}"
        body = _compose_email_body(action_type, payload)
        _send_email(recipient, subject, body)
    else:
        print(f"action_agent: no handler for action_type '{action_type}'")


class ActionAgent:
    def write_pending_action(
        self,
        action_type: str,
        payload: dict,
        proposed_by: str,
        bq_client: bigquery.Client = None,
    ) -> str:
        client = bq_client or _get_client()
        action_id = str(uuid.uuid4())
        cfg = bigquery.QueryJobConfig(query_parameters=[
            bigquery.ScalarQueryParameter("action_id", "STRING", action_id),
            bigquery.ScalarQueryParameter("action_type", "STRING", action_type),
            bigquery.ScalarQueryParameter("payload", "STRING", json.dumps(payload)),
            bigquery.ScalarQueryParameter("proposed_by", "STRING", proposed_by),
            bigquery.ScalarQueryParameter("created_at", "TIMESTAMP", datetime.now(timezone.utc).isoformat()),
        ])
        client.query(
            f"INSERT INTO `{_TABLE}` "
            f"(action_id, action_type, payload, status, proposed_by, approved_by, created_at, executed_at) "
            f"VALUES (@action_id, @action_type, @payload, 'pending', @proposed_by, NULL, @created_at, NULL)",
            job_config=cfg,
        ).result()
        return action_id

    def _poll_once(self, bq_client: bigquery.Client = None) -> list[str]:
        client = bq_client or _get_client()
        rows = list(client.query(
            f"SELECT * FROM `{_TABLE}` WHERE status = 'approved' ORDER BY created_at ASC"
        ).result())
        executed = []
        for row in rows:
            row = dict(row)
            try:
                _execute_action(row)
                now = datetime.now(timezone.utc).isoformat()
                client.query(
                    f"UPDATE `{_TABLE}` SET status = 'executed', executed_at = TIMESTAMP('{now}') "
                    f"WHERE action_id = '{row['action_id']}'"
                ).result()
                executed.append(row["action_id"])
            except Exception as e:
                print(f"action_agent: execution failed {row['action_id']}: {e}")
                client.query(
                    f"UPDATE `{_TABLE}` SET status = 'execution_failed' WHERE action_id = '{row['action_id']}'"
                ).result()
        return executed

    def start_poll_loop(self) -> None:
        def _loop():
            print(f"action_agent: poll loop started (every {_POLL_INTERVAL}s)")
            while True:
                try:
                    self._poll_once()
                except Exception as e:
                    print(f"action_agent: poll error: {e}")
                time.sleep(_POLL_INTERVAL)
        threading.Thread(target=_loop, daemon=True).start()
